name: eval_lmt-160m
harness:
  tasks:
    - arc_easy
    - arc_challenge
    - task: boolq
      dataset_kwargs:
        trust_remote_code: true
    - hellaswag
    - piqa
    - task: social_iqa
      dataset_kwargs:
        trust_remote_code: true
    - winogrande
validation:
  max_steps: 1000
generator:
  max_tokens: 16384
  dtype: bf16
pat:
  insert_svd_modules: true
