name: lmt-160m
dump_dir: /home/lvj/local/checkpoints/lmt-160m
steps: 120_000
probe_freq: null
grad_acc_steps: 2
seed: 777

optim:
  lr: 3e-4
  weight_decay: 0.1
  warmup: 5000
  lr_min_ratio: 1e-6
  clip: 1.0

distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  dim: 768
  n_layers: 12
  n_heads: 12

data:
  root_dir: /home/lvj/shared/datasets
  sources:
    dclm_baseline_1.0_10prct_shuffled: 1.0
  batch_size: 16
  prefetch_size: 1024
  seq_len: 2048
  n_views: 2
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    name: tiktoken
    path: /fsx-parq/lvj/hub/models--meta-llama--Llama-3.1-8B/original/tokenizer.model

profiling:
  run: true
  mem_warmup: 0
  mem_steps: 4
  profile_warmup: 100
  profile_steps: 4

checkpoint:
  dump:
    every: 2500
    keep: 3
  eval:
    every: 5000
    keep: -1

logging:
  freq: 1
  wandb:
    name: lmt-160m
    project: lingua

eval:
  harness:
    tasks:
      - arc_easy
      - arc_challenge
      - task: boolq
        dataset_kwargs:
          trust_remote_code: true
      - hellaswag
      - piqa
      - task: social_iqa
        dataset_kwargs:
          trust_remote_code: true
      - winogrande
  validation:
    max_steps: 1000
  generator:
    max_tokens: 16384
    dtype: bf16
